name: Mercadito Frontend CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Retry install dependencies
        run: |
          for i in 1 2 3; do
            npm install --legacy-peer-deps && break || sleep 10
          done

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u mpiccinini --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/mpiccinini/mercadito-frontend
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/mpiccinini/mercadito-frontend
          docker push $IMAGE_NAME:latest
