name: Mercadito Frontend CI

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Docker image
        run: docker build -t mercadito-frontend .

      - name: Run Expo Web in background
        run: |
          docker run -d -p 19006:19006 --name mercadito-check mercadito-frontend
          sleep 15

      - name: Health check on Expo server
        run: |
          curl --fail http://localhost:19006 || (echo "Expo server did not respond" && exit 1)

      - name: Stop container
        run: docker stop mercadito-check
